### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by mi804** [sollan/pdf2markup#1]
Hello,

I noticed that this repository does not include any license file. According to general copyright law, code without an explicit license defaults to "all rights reserved"[1](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)[3](https://www.quora.com/If-a-publicly-published-project-has-no-license-on-Github-Does-it-mean-I-can-use-the-source-code). Therefore, I would like to confirm whether it is permissible to use the code in this repository for commercial purposes?

If it is permissible, could you please add a clear license file so that we can comply with the relevant terms of use? If it is not permissible, please let us know as well.

Thank you!

**Comment by sollan** [comment]
Hi! Thanks for asking! I didn't expect interest in this project for commercial purposes, so didn't add a license in the first place. There's now a license provided.
